# Site settings
title: Shashank P. Rao
email: s.p.rao@student.tudelft.nl
description: > # Writer Theme is a responsive template
 CS Grad @TU Delft, Developer, Machine Learning (Deep Learning) Engineer & Researcher
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://shashankpr.github.io" # the base hostname & protocol for your site
disqus_shortname: "shashankpr"
comments: true
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  #Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
  #Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/shashank', 'fa-user']
single_footer: '<p>Learning has no end. Writer &copy; 2018 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
    Writer: ['Writer 2018', '/author/shashank']


# Build settings
# markdown: kramdown
